project:
  type: website
  output-dir: docs

website:
  title: "EdaaG's Analytics Lab"
  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: About Me
        href: about.qmd
      - text: My Posts
        href: posts.qmd
      - text: "EMU660 Coursework"
        menu:
          - text: Assignments
            href: assignments.qmd
          - text: Project
            href: project.qmd
    tools:
      - icon: github
        href: https://github.com/edagonen
      - icon: linkedin
        href: https://www.linkedin.com/in/edagonen/

  sidebar:
    - title: "Assignments"
      style: "docked"
      search: true
      contents:
        - text: "Assignments"
          href: assignments.qmd
        - text: "On Data Science and Industrial Engineering"
          href: assignments/datascience.qmd
        - text: "MRCars Statistics"
          href: assignments/statisticsofmrcars.qmd
        - text: "Handling Missing Values"
          href: assignments/handlingna.qmd

  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - EMU660 - Spring 2024"
    border: true

format:
  html:
    toc: true
    toc-location: left
    theme: 
      light: simplex
      dark: cyborg
    css: styles.css

editor: visual