---
title: "About Me" 
sidebar: false 
---

## [Short Biography]{style="color:red;"}

As an **industrial engineer** with a passion for data analysis, broadcasting, and artificial intelligence, I have built my career on exploring innovative solutions in these fields. After graduating from TOBB University, I began working as a data analyst in the broadcasting sector, specifically at TRT1, where I focused on broadcast planning and data analysis. 

Currently, I am pursuing a master's degree in industrial engineering while developing projects that integrate AI and innovation into the broadcasting industry. I also share insights on industry trends through blog writing and continuously work on enhancing my professional expertise.

## [Education]{style="color:red;"}

-   **M.S, Industrial Engineering**, Hacettepe University, *Turkey*
    -   *2025 - ongoing*

<!-- -->

-   **M.S, Business Administration**, Hacettepe University, *Turkey*
    -   *2022 - 2023*

<!-- -->

-   **B.S, Industrial Engineering**, TOBB University of Economics and Technology, *Turkey*
    -   *2015 - 2020*

## [Work Experience]{style="color:red;"}

-   **TRT**, Planning Specialist, Turkey

    -   *Dec 2021 - ongoing*

        ***Broadcast Planning & Performance Analysis**: Managing and monitoring TV broadcasts, analyzing rating performance, and optimizing scheduling and discount strategies.*

        ***Data-Driven Decision Making**: Conducting data analysis, preparing reports, and ensuring effective team coordination for strategic planning.*

-   **LC WAIKIKI ,** International Store Merchandiser, Turkey

    -   *Jan 2021 - Dec 2021*

        *Managing international store stocks, analyzing performance metrics, and optimizing shipping strategies based on regional clothing preferences.*

        *Developing and implementing discount strategies to enhance sales*.

-   **TURK PATENT VE MARKA KURUMU**, Intern, Turkey

    -   *Dec 2019 - Sep 2019*

-   **MAN TURKIYE**, Quality Control Engineer Intern, Turkey

    -   *Jan 2019 - Apr 2019*

-   **ERSA OFIS MOBILYALARI** , IT Intern, Turkey

    -   *Aug 2018- May 2019*\

## [Competencies]{style="color:red;"}

-   **Mathematical Modelling**
-   **MS Office**
-   **R**
-   **CPLEX**
-   **MySQL**
-   **MS Office**

## [Hobbies]{style="color:red;"}
